project_id = "modgiywtysnpnyrgwuhn"

[functions.validate-vat]
verify_jwt = false

[functions.discogs-search]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.create-pro-customer]
verify_jwt = false

[functions.admin-cbac]
verify_jwt = false