project_id = "modgiywtysnpnyrgwuhn"

[functions.validate-vat]
verify_jwt = false

[functions.discogs-search]
verify_jwt = false

[functions.exchange-rates]
verify_jwt = false

[functions.create-pro-customer]
verify_jwt = false

[functions.admin-cbac]
verify_jwt = false

[functions.ship24-tracking]
verify_jwt = false

[functions.payment-create-setup-intent]
verify_jwt = false

[functions.payment-create-subscription]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.payment-cancel-subscription]
verify_jwt = false
